name: cql
description: Attempt to Support the CQL Library in Dart.
version: 0.0.0-dev1
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/cql

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  fhir:
    path: ../fhir/fhir
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  units_converter: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.6
