name: cql
description: Attempt to Support the CQL Library in Dart.
version: 0.0.0-dev1
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/cql

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  antlr4: ^4.13.1
  collection: ^1.18.0
  fhir_dstu2:
    path: ../fhir_dstu2
  fhir_path:
    path: ../fhir_path
  fhir_primitives:
    path: ../fhir_primitives
  fhir_r4:
    path: ../fhir_r4
  fhir_r5:
    path: ../fhir_r5
  fhir_r6:
    path: ../fhir_r6
  fhir_stu3:
    path: ../fhir_stu3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  petitparser: ^6.0.2
  ucum:
    path: ../ucum
  uuid: ^4.3.3
  xml: ^6.5.0
  xml2json: ^6.2.2
  xml_serializable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  # test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - cql/
    - json/

dependency_overrides:
  meta: ^1.12.0