// Regenerates a stored modelinfo Dart data file from an official HL7
// modelinfo XML, using StandardModelInfoReader (verified lossless — see
// tool/verify_modelinfo_reader.dart). The previously stored data files were
// produced by an older pipeline that dropped `elementType` from every
// ListTypeSpecifier and lost some element declarations entirely.
//
// Usage: dart run tool/regenerate_modelinfo.dart <xml-path> <out-dart-path> <symbol>
// e.g.:  dart run tool/regenerate_modelinfo.dart \
//          /tmp/official-modelinfo-4.0.1.xml \
//          lib/model/serializing/model_info/fhir-modelinfo-4.0.1.dart \
//          fhirmodelinfo401
//
// Progress streams incrementally to stdout (flushed) and the output file is
// written once fully validated (read → toJson → fromJson → re-verify).
import 'dart:convert';
import 'dart:io';

import 'package:cql/cql.dart';

void main(List<String> args) {
  if (args.length != 3) {
    stderr
        .writeln('usage: regenerate_modelinfo.dart <xml> <out.dart> <symbol>');
    exit(2);
  }
  final xmlPath = args[0];
  final outPath = args[1];
  final symbol = args[2];

  void log(String s) {
    stdout.writeln(s);
  }

  log('reading $xmlPath ...');
  final xml = File(xmlPath).readAsStringSync();
  final mi = StandardModelInfoReader().read(xml);
  log('parsed: ${mi.name} ${mi.version} — typeInfo=${mi.typeInfo.length} '
      'conversionInfo=${mi.conversionInfo.length}');

  log('serializing to JSON ...');
  final json = mi.toJson();
  final jsonText = jsonEncode(json);
  log('json length: ${jsonText.length}');

  // Round-trip validation: fromJson(toJson(x)) must preserve the structures
  // the translator depends on.
  log('round-trip validating ...');
  final rt = ModelInfo.fromJson(jsonDecode(jsonText) as Map<String, dynamic>);
  final failures = <String>[];
  if (rt.typeInfo.length != mi.typeInfo.length) {
    failures.add('typeInfo count ${rt.typeInfo.length} != '
        '${mi.typeInfo.length}');
  }
  if (rt.conversionInfo.length != mi.conversionInfo.length) {
    failures.add('conversionInfo count ${rt.conversionInfo.length} != '
        '${mi.conversionInfo.length}');
  }

  ClassInfo? classOf(ModelInfo m, String name) => m.typeInfo
      .whereType<ClassInfo>()
      .where((c) => c.name == name)
      .firstOrNull;
  ClassInfoElement? elementOf(ClassInfo? c, String name) =>
      c?.element?.where((e) => e.name == name).firstOrNull;

  // ListTypeSpecifier element types must survive the round trip (this is
  // exactly what the old pipeline lost).
  for (final probe in [
    ('Account', 'identifier', 'Identifier'),
    ('Patient', 'name', 'HumanName'),
    ('Observation', 'category', 'CodeableConcept'),
  ]) {
    final spec =
        elementOf(classOf(rt, probe.$1), probe.$2)?.elementTypeSpecifier;
    if (spec is! ListTypeSpecifierModel || spec.elementType != probe.$3) {
      failures.add('${probe.$1}.${probe.$2}: expected '
          'ListTypeSpecifier(elementType: ${probe.$3}), got '
          '${spec is ListTypeSpecifierModel ? 'List(${spec.elementType})' : spec?.runtimeType}');
    }
  }
  // Choice types must survive.
  final valueSpec =
      elementOf(classOf(rt, 'Observation'), 'value')?.elementTypeSpecifier;
  if (valueSpec is! ChoiceTypeSpecifierModel ||
      (valueSpec.choice?.length ?? 0) != 11) {
    failures.add('Observation.value: expected ChoiceTypeSpecifier(11), got '
        '${valueSpec?.runtimeType}');
  }
  // A conversion must survive.
  final toQty = rt.conversionInfo
      .where((c) => c.functionName == 'FHIRHelpers.ToQuantity')
      .firstOrNull;
  if (toQty == null ||
      toQty.fromType != 'Quantity' ||
      toQty.toType != 'System.Quantity') {
    failures.add('ToQuantity conversion lost: $toQty');
  }

  if (failures.isNotEmpty) {
    stderr.writeln('ROUND-TRIP FAILURES:');
    failures.forEach(stderr.writeln);
    exit(1);
  }
  log('round-trip OK.');

  // Raw triple-quoted string + jsonDecode avoids Dart `$`-interpolation and
  // quote-escaping hazards in the embedded JSON.
  if (jsonText.contains("'''")) {
    stderr.writeln("JSON contains ''' — cannot embed as raw string");
    exit(1);
  }
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/regenerate_modelinfo.dart from the')
    ..writeln('// official HL7 modelinfo XML. Do not edit by hand.')
    ..writeln('// Source: ${xmlPath.split('/').last}')
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln("import 'package:cql/cql.dart';")
    ..writeln()
    ..writeln('final $symbol =')
    ..writeln(
        '    ModelInfo.fromJson(jsonDecode(_json) as Map<String, dynamic>);')
    ..writeln()
    ..writeln("const _json = r'''")
    ..writeln(jsonText)
    ..writeln("''';");
  File(outPath).writeAsStringSync(out.toString());
  log('wrote $outPath (${out.length} chars), symbol: $symbol');
}
